main:
  - name: Home
    url: /
    weight: 1
  - name: Publications
    url: /#publications
    weight: 2
  - name: Projects
    url: /#projects
    weight: 3
  - name: Teaching
    url: /#teaching
    weight: 4
  - name: Curriculum Vitæ
    url: /#Vitæ
    weight: 5
