# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system  # System matches the user's OS setting (light/dark mode)
  color: blue   # Customize the primary color to fit your branding

assets:
  css:
    - css/custom.css


# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: 'Khalil Bachiri'
    description: 'Khalil Bachiri, PhD Student in Data Science and Machine Learning.'
    twitter: 'khalilbachiri'  # Your Twitter username without '@'
    linkedin: 'linkedin.com/in/khalil-bachiri-690726200'
    
  analytics:
    google_analytics: 'YOUR-GOOGLE-ANALYTICS-ID'  # Add if you want to track site visitors
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''  # Add your Google site verification code here
    baidu: ''   # Add your Baidu site verification code here
# Avatar/Profile Image


# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      text: "Khalil Bachiri"  # Your name displayed in the navbar
    social:
      - icon: "graduation-cap"
        icon_pack: "fas"
        url: "https://scholar.google.com/citations?user=Bgd_tsAAAAAJ&hl=fr"
        name: "Google Scholar"
      - icon: "linkedin"
        icon_pack: "fab"
        url: "linkedin.com/in/khalil-bachiri-690726200"
        name: "LinkedIn"
      - icon: "github"
        icon_pack: "fab"
        url: "https://github.com/Khalil-BACHIRI"
        name: "GitHub"
      - icon: "database"
        icon_pack: "fas"
        url: "https://dblp.org/pid/YOUR_DBLP_ID"
        name: "DBLP"

# Site footer
footer:
  copyright:
    notice: 'Â© {year} Khalil Bachiri. All rights reserved.'
    license:
      enable: true
      allow_derivatives: false
      share_alike: false
      allow_commercial: false
  social:
    - icon: "graduation-cap"
      icon_pack: "fas"
      url: "https://scholar.google.com/citations?user=Bgd_tsAAAAAJ&hl=fr"
      name: "Google Scholar"
    - icon: "linkedin"
      icon_pack: "fab"
      url: "linkedin.com/in/khalil-bachiri-690726200"
      name: "LinkedIn"
    - icon: "github"
      icon_pack: "fab"
      url: "https://github.com/Khalil-BACHIRI"
      name: "GitHub"
    - icon: "database"
      icon_pack: "fas"
      url: "https://dblp.org/pid/YOUR_DBLP_ID"
      name: "DBLP"
# Localization
locale:
  date_format: '31 Dec 2024'  # Customize the date format (e.g., "31 Dec 2024")
  time_format: '05:04'       # 24-hour time format

# Site features
features:
  math:
    enable: true  # Enable math rendering for LaTeX equations if needed
  privacy_pack:
    enable: true  # Enable privacy features for GDPR compliance

  pagination:
    enable: false
